#!/bin/sh
chv_ConfigName="$CH_ConfigName"
chv_ConfigFile="$CH_ConfigFile"

if [ -z "$chv_ConfigName" ]; then
    chv_ConfigName="CH_Config"
fi

if [ -z "$chv_ConfigFile" ]; then
    chv_ConfigFile="config.cnf"
fi

if [ ! -f $chv_ConfigFile ]; then
    echo "$chv_ConfigFile not exists" >&2
else
    eval $( echo "declare -A $chv_ConfigName=()" )
    eval $( 
        cat "$chv_ConfigFile" | \
        grep "=" | \
        egrep -v "^#.*" | \
        sed s/\\\"/\"/g | \
        awk -F '=' '
            function trim(str) {
                sub("^[ ]*", "", str);
                sub("[ ]*$", "", str);
                sub("^[\"]*", "", str);
                sub("[\"]*$", "", str);
                return str
            }
            {
                if(trim($1) != ""){
                    printf("'$chv_ConfigName'[\"%s\"]=\"%s\"\n", trim($1), trim($2)); 
                }
            }
        '
    )
fi